# Generated by Django 4.2.3 on 2023-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=5000, unique=True, verbose_name='Номер телефона'),
        ),
    ]
